default: &default
  adapter: postgresql
  encoding: unicode
  port: 5433
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chat_development

test:
  <<: *default
  database: chat_test

production:
  <<: *default
  database: chat_production
  username: chat
  password: <%= ENV['RAILS_CHAT_TUTORIAL_DATABASE_PASSWORD'] %>
